# Site settings
title: Tri-Valley Center for Human Potential
email: admin@trivalleycenterforhumanpotential.org
description: > # this means to ignore newlines until "baseurl:"
  The Tri-Valley Center for Human Potential is an independent research
  institute studying the human mind.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trivalleycenterforhumanpotential.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
